import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeHarness, getHarnessStatus, validateAllDocuments, validateDocument } from "../src/index.js";
import { detectCapabilities } from "../src/core/applicability/detect.js";

const roots: string[] = [];
const architectureSections = ["System Overview", "Technology Architecture", "Repository Structure", "Major Components", "Dependency Boundaries", "Data Flow", "State Management", "Interfaces and Integrations", "Runtime and Deployment", "Cross-Cutting Concerns", "Architectural Invariants", "Architectural Decisions", "Known Constraints", "Evolution Guidance"];
const architectureDocument = (includeBackend: boolean) => `# Architecture\n\n${architectureSections.map((section) => `## ${section}\n\nVerified architecture information for ${section}.${section === "Repository Structure" && includeBackend ? "\n\n### Backend Structure\n\n- \`src/server.ts\` — owns the verified HTTP server entry point and backend runtime boundary.\n\n#### Dependency Boundaries\n\n- HTTP transport may call application interfaces; application code must not depend on transport callbacks." : ""}`).join("\n\n")}`;
async function project(files: Record<string, string> = {}): Promise<string> { const root = await mkdtemp(join(tmpdir(), "aiharness-applicability-")); roots.push(root); await initializeHarness(root); for (const [path, content] of Object.entries(files)) { const target = join(root, path); await mkdir(join(target, ".."), { recursive: true }); await writeFile(target, content); } return root; }
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });

describe("document applicability", () => {
  it("marks core templates pending in an empty initialized repository", async () => { const root = await project(); const results = await validateAllDocuments(root); const status = await getHarnessStatus(root); expect(results.map((result) => result.path)).toEqual(["AGENTS.md", "ARCHITECTURE.md"]); expect(status.documents?.find((item) => item.path === "AGENTS.md")?.readiness).toBe("pending"); expect(status.documents?.find((item) => item.path === "docs/FRONTEND.md")?.readiness).toBe("not_applicable"); });
  it("requires design and frontend documents when frontend source is detected", async () => { const root = await project({ "src/App.tsx": "import React from 'react'; export const App = () => <main />;" }); const status = await getHarnessStatus(root); expect(status.documents?.find((item) => item.path === "docs/DESIGN.md")?.applicability).toBe("required"); expect(status.documents?.find((item) => item.path === "docs/FRONTEND.md")?.applicability).toBe("required"); });
  it("requires the backend guide when server behavior is detected", async () => { const root = await project({ "src/server.ts": "import { createServer } from 'node:http'; createServer(() => undefined).listen(3000);" }); const status = await getHarnessStatus(root); expect(status.documents?.find((item) => item.path === "docs/BACKEND.md")).toMatchObject({ applicability: "required", readiness: "pending" }); });
  it("requires a backend directory map in architecture when backend capabilities are detected", async () => { const root = await project({ "src/server.ts": "import { createServer } from 'node:http'; createServer(() => undefined).listen(3000);", "ARCHITECTURE.md": architectureDocument(false) }); await expect(validateDocument(join(root, "ARCHITECTURE.md"))).resolves.toMatchObject({ valid: false, issues: expect.arrayContaining([expect.objectContaining({ code: "CONDITIONAL_SUBSECTION_MISSING" })]) }); await writeFile(join(root, "ARCHITECTURE.md"), architectureDocument(true)); await expect(validateDocument(join(root, "ARCHITECTURE.md"))).resolves.toMatchObject({ valid: true }); });
  it("requires verified backend paths, path responsibilities, and dependency boundaries", async () => { const root = await project({ "src/server.ts": "import { createServer } from 'node:http'; createServer(() => undefined).listen(3000);", "ARCHITECTURE.md": architectureDocument(true).replace("`src/server.ts` — owns the verified HTTP server entry point and backend runtime boundary.", "`src/missing-server.ts`") }); const result = await validateDocument(join(root, "ARCHITECTURE.md")); expect(result.issues.map((item) => item.code)).toEqual(expect.arrayContaining(["BACKEND_PATH_UNVERIFIED", "BACKEND_PATH_RESPONSIBILITY_MISSING", "BACKEND_PATH_REFERENCE_MISSING"])); await writeFile(join(root, "ARCHITECTURE.md"), architectureDocument(true).replace("#### Dependency Boundaries\n\n- HTTP transport may call application interfaces; application code must not depend on transport callbacks.", "")); await expect(validateDocument(join(root, "ARCHITECTURE.md"))).resolves.toMatchObject({ valid: false, issues: expect.arrayContaining([expect.objectContaining({ code: "CONDITIONAL_REQUIRED_SUBSECTION_MISSING" })]) }); });
  it("recommends security and reliability documents for an API with environment configuration", async () => { const root = await project({ "src/server.ts": "import { createServer } from 'node:http'; const key = process.env.API_KEY; createServer((req) => req.url).listen(3000);" }); const status = await getHarnessStatus(root); expect(status.documents?.find((item) => item.path === "docs/SECURITY.md")).toMatchObject({ applicability: "recommended", readiness: "pending" }); expect(status.documents?.find((item) => item.path === "docs/RELIABILITY.md")).toMatchObject({ applicability: "recommended", readiness: "pending" }); });
  it("does not read .env content while detecting environment references", async () => { const root = await project({ ".env": "TOP_SECRET_VALUE=do-not-expose", "src/config.ts": "export const key = process.env.API_KEY;" }); const report = await detectCapabilities(root); expect(report.capabilities).toContain("secrets_configuration"); expect(JSON.stringify(report)).not.toContain("do-not-expose"); });
  it("reports stable capability reasons without forcing optional documents", async () => { const root = await project({ "src/jobs.ts": "export const worker = () => queue.add('task');" }); const status = await getHarnessStatus(root); expect(status.capabilities).toEqual(expect.arrayContaining(["background_jobs", "queue"])); expect(status.documents?.find((item) => item.path === "docs/RELIABILITY.md")?.reasons.length).toBeGreaterThan(0); expect(status.documents?.find((item) => item.path === "docs/QUALITY_SCORE.md")?.applicability).toBe("optional"); });
});
