import { readdir, readFile } from "node:fs/promises";
import { join, extname } from "node:path";
import type { Capability } from "../schema/types.js";
import type { CapabilityReport } from "./types.js";

const sourceExtensions = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".rs"]);
async function source(root: string): Promise<string> { const out: string[] = []; async function visit(dir: string): Promise<void> { for (const entry of await readdir(dir, { withFileTypes: true })) { if (["node_modules", ".git", "dist", ".xxx"].includes(entry.name)) continue; const path = join(dir, entry.name); if (entry.isDirectory()) await visit(path); else if (sourceExtensions.has(extname(entry.name))) out.push(await readFile(path, "utf8")); } } await visit(root); return out.join("\n"); }
export async function detectCapabilities(root: string): Promise<CapabilityReport> { const text = await source(root); const found: Partial<Record<Capability, string[]>> = {}; const add = (capability: Capability, match: RegExp, reason: string) => { if (match.test(text)) (found[capability] ??= []).push(reason); };
  add("frontend", /from\s+["'](?:react|vue|svelte)|<\/?[A-Z][\w.]*/i, "frontend source usage"); add("server_api", /createServer|express\(|fastify\(|router\.(get|post|put|delete)|Request\s*\)/i, "server/API handler usage"); add("authentication", /\b(authenticate|authorization|jsonwebtoken|jwt|oauth|session)\b/i, "authentication-related source usage"); add("external_input", /req\.(body|query|params)|process\.argv|FormData|URLSearchParams/i, "external input handling"); add("secrets_configuration", /process\.env\.|Deno\.env\./, "environment configuration reference"); add("sensitive_data", /\b(password|credential|token|ssn|payment|card number)\b/i, "sensitive-data terminology in source"); add("background_jobs", /\b(cron|schedule|worker|background job)\b/i, "background-job source usage"); add("queue", /\b(queue|bullmq|rabbitmq|sqs)\b/i, "queue source usage"); add("external_dependency", /\b(fetch\(|axios\.|https?\.request|prisma\.|mongoose\.|redis\.)/i, "external service or persistence usage"); add("production_runtime", /listen\(|createServer|Dockerfile|process\.on\(["']SIG/i, "runtime entry-point usage"); return { capabilities: Object.keys(found) as Capability[], reasons: found }; }
