import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { DocumentReadiness, HarnessStatus, HarnessState, Inspection } from "../types.js";
import { exists, findProjectRoot } from "./paths.js";
import { validateAllDocuments } from "./validate.js";
import { loadBundledSchemas } from "./schema/loader.js";
import { detectCapabilities } from "./applicability/detect.js";
import { resolveApplicability } from "./applicability/resolve.js";
export async function getHarnessStatus(from = process.cwd()): Promise<HarnessStatus> { const root = await findProjectRoot(from); const initialized = await exists(join(root, ".xxx/state.json")); if (!initialized) return { initialized, root, documentCount: 0 }; const state = JSON.parse(await readFile(join(root, ".xxx/state.json"), "utf8")) as HarnessState; const inspection = await exists(join(root, ".xxx/inspect.json")) ? JSON.parse(await readFile(join(root, ".xxx/inspect.json"), "utf8")) as Inspection : undefined; const [schemas, capabilities, validations] = await Promise.all([loadBundledSchemas(), detectCapabilities(root), validateAllDocuments(root)]); const validationByPath = new Map(validations.map((result) => [result.path, result])); const documents = schemas.map((schema) => { const item = resolveApplicability(schema, capabilities); const validation = validationByPath.get(schema.path); const onlyPlaceholders = validation && validation.issues.length > 0 && validation.issues.every((issue) => issue.code === "PLACEHOLDER_REMAINING"); const readiness: DocumentReadiness = item.state === "not_applicable" ? "not_applicable" : item.state === "optional" ? "optional" : !validation || onlyPlaceholders ? "pending" : validation.valid ? "valid" : validation.issues.some((issue) => issue.code === "DOCUMENT_MISSING") ? "pending" : "invalid"; return { path: schema.path, applicability: item.state, reasons: item.reasons, readiness, ...(validation ? { valid: validation.valid } : {}) }; }); return { initialized, root, state, ...(inspection ? { inspection } : {}), documentCount: validations.length, capabilities: capabilities.capabilities, documents }; }
