#!/usr/bin/env node
import { Command } from "commander";
import { createProposal, exploreHarness, getApplyInstructions, getHarnessStatus, getProjectContext, initializeHarness, inspectProject, validateAllDocuments, validateDocument, verifyChange } from "./index.js";

const program = new Command().name("AIharness").description("Repository-level AI development harness").version("1.0.1");
program.command("init [directory]").description("Initialize a harness in a project directory").action(async (directory: string | undefined) => { const result = await initializeHarness(directory); for (const file of result.files) console.log(`${file.status.padEnd(8)} ${file.path}`); });
program.command("inspect [directory]").description("Inspect a project and persist its facts").option("--json", "Write structured JSON to stdout").action(async (directory: string | undefined) => { console.log(JSON.stringify(await inspectProject(directory), null, 2)); });
program.command("context <domain> [directory]").description("Read documents for a project domain").option("--json", "Write structured JSON to stdout").action(async (domain: string, directory: string | undefined, options: { json?: boolean }) => { const result = await getProjectContext(domain, directory); if (options.json) console.log(JSON.stringify(result, null, 2)); else console.log(result.documents.map((document) => `# ${document.path}\n\n${document.content}`).join("\n\n")); });
program.command("validate [file]").description("Validate one managed document or all applicable managed documents").option("--json", "Write structured JSON to stdout").action(async (file: string | undefined, options: { json?: boolean }) => { const result = file ? [await validateDocument(file)] : await validateAllDocuments(); if (options.json) console.log(JSON.stringify(file ? result[0] : result, null, 2)); else for (const item of result) { console.log(`${item.valid ? "valid" : "invalid"} ${item.path}`); for (const issue of item.issues) console.log(`  ${issue.severity} ${issue.code ?? "VALIDATION"}: ${issue.message}`); } if (result.some((item) => !item.valid)) process.exitCode = 1; });
program.command("status [directory]").description("Show harness status").action(async (directory: string | undefined) => { console.log(JSON.stringify(await getHarnessStatus(directory), null, 2)); });
program.command("explore [directory]").description("Explore repository facts and documentation prerequisites without writing files").option("--json", "Write structured JSON to stdout").action(async (directory: string | undefined, options: { json?: boolean }) => { const result = await exploreHarness(directory); if (options.json) console.log(JSON.stringify(result, null, 2)); else { console.log(`Explore ${result.root}`); console.log(`Suggested documents: ${result.suggestedDocuments.join(", ") || "none"}`); for (const question of result.questions) console.log(`- ${question}`); console.log(result.next); } });
program.command("propose <change>").description("Create a documentation-change proposal from explored evidence").requiredOption("--documents <paths>", "Comma-separated managed document paths").option("--json", "Write structured JSON to stdout").action(async (change: string, options: { documents: string; json?: boolean }) => { const result = await createProposal(change, options.documents.split(",")); if (options.json) console.log(JSON.stringify(result, null, 2)); else { console.log(`created ${result.proposalPath}`); console.log(result.next); } });
program.command("apply <change>").description("Validate a proposal and output instructions for an agent to update its target documents").option("--json", "Write structured JSON to stdout").action(async (change: string, options: { json?: boolean }) => { const result = await getApplyInstructions(change); if (options.json) console.log(JSON.stringify(result, null, 2)); else { console.log(`${result.valid ? "ready" : "blocked"} ${result.proposalPath}`); for (const instruction of result.instructions) console.log(`- ${instruction}`); } if (!result.valid) process.exitCode = 1; });
program.command("verify <change>").description("Verify a documentation proposal and every target document").option("--json", "Write structured JSON to stdout").action(async (change: string, options: { json?: boolean }) => { const result = await verifyChange(change); if (options.json) console.log(JSON.stringify(result, null, 2)); else { console.log(`${result.valid ? "valid" : "invalid"} ${change}`); for (const issue of result.issues) console.log(`  ${issue.severity} ${issue.code ?? "VERIFICATION"}: ${issue.message}`); } if (!result.valid) process.exitCode = 1; });
program.parseAsync().catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
